#!/bin/bash
#This sssumes that gh-pages is checked out at DEMO (git worktree add DEMO gh-pages)
sed -f www/deploy.sed www/raze.js > DEMO/raze.js
sed -f www/deploy.sed www/index.html > DEMO/index.html
cp pkg/raze_bg.wasm pkg/raze.js DEMO/pkg/
