[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
zxspectrum-raze = { path = "../raze" }
easy-imgui = "0.24"
easy-imgui-sdl3 = "0.24"
easy-imgui-opengl = "0.3.0"
easy-imgui-filechooser = { version = "0.5", features = ["zip"] }
cpal = "0.18"
anyhow = "1.0.98"
sdl3 = "0.18"
thiserror = "2.0.17"
fancy-duration = "0.9.2"
fftw = "0.8.0"
log = "0.4.29"
env_logger = "0.11.9"
zip = "8.5.0"
